apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.studentName }}
  namespace: {{ .Values.studentName }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  index.html: |
    <html><head><title>Hello Nikoloz</title></head><body>Hello Nikoloz</body></html>