apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-{{ .Values.studentName }}
  namespace: {{ .Values.studentName }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:      
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: web-server-{{ .Values.studentName }}
          image: "{{ .Values.deployment.repository }}:{{ .Values.deployment.version }}"
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
      volumes:
        - name: html-content
        #4.c
          configMap:
            name: {{ .Values.studentName }}
      
