apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.studentName }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  hosts:
    - {{ .Values.virtualService.host}}
  gateways:
    - {{ .Values.virtualService.gateway}}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: 80